image: php:7.0
 
stages:
  - package
phar:
  stage: package
  script:
   - cd /builds/Pogogo007/
   - php EconomyPlus/scripts/mkplugin.php EconomyPlus EconomyPlus/src
   - mv EconomyPlus*.phar EconomyPlus/
  artifacts:
   paths:
     - EconomyPlus*.phar
